spring:
  datasource:
    password: "###hashtag###"
    url: "jdbc:mysql://localhost:3306/pinger"
    username: "dreek"

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      show-sql: true
  web:
    resources:
      static-locations: classpath:/
